Auth controller
Drunken-Dragon/silex-lp pull request #6
Opened 2017-12-06 23:50 UTC by Drunken-Dragon

Aplikacja zwraca błąd 'Identifier "form" is not defined.'

Przyczyna błędu umyka mi już o tej porze...Proszę o review.

2017-12-07 18:42 UTC, nexik requested changes

2017-12-07 18:42 UTC, nexik commented on src/app.php
> +    return new \Controller\AuthController($app['twig'], $app['form'], new \Controller\LoginFormController($app['form.factory']));
constructor przyjmuje tylko 2 argumenty a ty przekazujesz 3

nie masz zdefiniowane $app['form'] wiec silex nie wie co to jest 'form'

musisz zdefiniowac $app['form'] = $app['form.factory']->createBuilder(FormType::class, $data) ....

2017-12-09 12:37 UTC, nexik requested changes

2017-12-09 12:37 UTC, nexik commented on src/Controller/AuthController.php
> +    public function __construct($app, $db)
jak nie korzystasz z $db to nie wymagaj tego w construct

2017-12-09 12:37 UTC, nexik commented on src/app.php
> +    return new \Controller\AuthController($app, $db);
zmienna $db nie jest zdefiniowana.

2017-12-09 12:37 UTC, nexik commented on src/Controller/AuthController.php
> +
nie potrzbna pusta linia

2017-12-09 12:37 UTC, nexik commented on src/Controller/AuthController.php
> +                dump($app['session']);
takie rzeczy mozna lokalnie a ale nie kodzie "produkcyjnym" w  PR tak samo ten die()

2017-12-09 12:37 UTC, nexik commented on src/Controller/LoginFormController.php
> +//        $this->form = $formFactory->;
usuwamy nie komentujemy kodu

2017-12-09 12:37 UTC, nexik commented on src/Controller/LoginFormController.php
> +//        $this->app = $app;
usuwamy nie komentujemy kodu

2017-12-09 12:55 UTC, Drunken-Dragon commented
Nie skonczylem jeszcze tego etapu,stad sporo komentarzy. Dzisiaj chce dojsc
do etapu kiedy sorawdza sesje i wczytuje lp. Wtedy uporzadkuje kod przed
kolejnym pushem.


09.12.2017 13:37 "Tomasz Ślązok" <notifications@github.com> napisał(a):

*@nexik* requested changes on this pull request.
------------------------------

In src/Controller/AuthController.php
<https://github.com/Drunken-Dragon/silex-lp/pull/6#discussion_r155921658>:

>      private $twig;
-    public function __construct($twig, $form)
+    private $db;
+
+    public function __construct($app, $db)

jak nie korzystasz z $db to nie wymagaj tego w construct
------------------------------

In src/app.php
<https://github.com/Drunken-Dragon/silex-lp/pull/6#discussion_r155921661>:

> @@ -50,7 +50,7 @@
 });

 $app['auth.controller'] = function () use ($app) {
-    return new \Controller\AuthController($app['twig'], $app['form'],
new \Controller\LoginFormController($app['form.factory']));
+    return new \Controller\AuthController($app, $db);

zmienna $db nie jest zdefiniowana.
------------------------------

In src/Controller/AuthController.php
<https://github.com/Drunken-Dragon/silex-lp/pull/6#discussion_r155921670>:

>      {
-        $form->handleRequest($request);
+        return $this->twig->render('login.html.twig', [
+            'form' => $this->form->createView()
+        ]);
+    }
+
+    public function loginAction(Request $request)
+    {
+

nie potrzbna pusta linia
------------------------------

In src/Controller/AuthController.php
<https://github.com/Drunken-Dragon/silex-lp/pull/6#discussion_r155921682>:

>
             if (password_verify($data['password'], $user[0]['password'])) {
+                dump($app['session']);

takie rzeczy mozna lokalnie a ale nie kodzie "produkcyjnym" w PR tak samo
ten die()
------------------------------

In src/Controller/LoginFormController.php
<https://github.com/Drunken-Dragon/silex-lp/pull/6#discussion_r155921695>:

> @@ -15,8 +15,8 @@ class LoginFormController

     public function __construct($formFactory)
     {
-        $this->form = $form;
-        $this->app = $app;
+//        $this->form = $formFactory->;

usuwamy nie komentujemy kodu
------------------------------

In src/Controller/LoginFormController.php
<https://github.com/Drunken-Dragon/silex-lp/pull/6#discussion_r155921699>:

> @@ -15,8 +15,8 @@ class LoginFormController

     public function __construct($formFactory)
     {
-        $this->form = $form;
-        $this->app = $app;
+//        $this->form = $formFactory->;
+//        $this->app = $app;

usuwamy nie komentujemy kodu

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Drunken-Dragon/silex-lp/pull/6#pullrequestreview-82324601>,
or mute the thread
<https://github.com/notifications/unsubscribe-auth/AWj0bKbxta7FmafiBNwIPbC4LXYC_ULMks5s-n75gaJpZM4Q4xia>
.

2017-12-09 13:20 UTC, nexik commented
ok spoko tak wiec bede czekac na part II :) milego weekendu.

2017-12-10 01:29 UTC, Drunken-Dragon commented
Part II ready :) Pora nieco się przespać...

2017-12-10 16:35 UTC, nexik requested changes

2017-12-10 16:35 UTC, nexik commented on src/Controller/AuthController.php
> +        $this->db = $app['db'];
Albo przekazujesz do constructora $db albo uzywasz $app['db'] musisz sie na cos zdecydowac.

2017-12-10 16:35 UTC, nexik commented on src/Controller/AuthController.php
> +        $this->session = $app['session'];
Albo przekazujesz do constructora $session albo uzywasz $app['session'] musisz sie na cos zdecydowac.

2017-12-10 16:35 UTC, nexik commented on src/Controller/LandingController.php
> +        $this->session = $app['session'];
Albo przekazujesz do constructora $session albo uzywasz $app['session'] musisz sie na cos zdecydowac.

2017-12-10 16:35 UTC, nexik commented on src/Controller/LandingController.php
> +        $this->twig = $app['twig'];
Albo przekazujesz do constructora $twig albo uzywasz $app['twig'] musisz sie na cos zdecydowac.

2017-12-10 16:35 UTC, nexik commented on src/routes.php
> +
puste linie podziedzy wowolaniami $app->get() mozna usuwac nie poprawiaja znaczaco czytelnosci kodu aby je dodawac

2017-12-10 16:35 UTC, nexik commented on src/Controller/AuthController.php
> +
ta pusta linia mozna usuwac nic nie wnosi

2017-12-10 16:35 UTC, nexik commented on src/Controller/AuthController.php
> +        return $this->twig->render('login.html.twig', array('form' => $form->createView()));
przed returnem dodajemy pusta linie aby bylo widac ze to jest najwazniejsza czesc metody

2017-12-10 17:40 UTC, Drunken-Dragon commented
Wprowadziłem Twoje poprawki oraz dodałem .env.

Wydaje mi się, że skorzystałem z .env poprawnie, jednak rzuca mi błąd:
An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO)

Czy możesz jutro na to zerknąć? Póki co nie znalazłem w necie rozwiązania które by mi pomogło...

2017-12-10 17:40 UTC, nexik approved these changes

2017-12-10 17:42 UTC, merged

2017-12-10 17:42 UTC, nexik commented
jedyny blad jaki widze to brak zaladowanie .dotenva w projekcie .env sam sie nie zaladuje

2017-12-10 18:10 UTC, Drunken-Dragon commented
czy to wymaga użycia jakiegoś osobnego service?

2017-12-10 18:42 GMT+01:00 Tomasz Ślązok <notifications@github.com>:

> jedyny blad jaki widze to brak zaladowanie .dotenva w projekcie .env sam
> sie nie zaladuje
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/Drunken-Dragon/silex-lp/pull/6#issuecomment-350564946>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AWj0bLyOAt8RAvnFeCWOuNjmBye9Bwrjks5s_Bf9gaJpZM4Q4xia>
> .
>

2017-12-10 18:17 UTC, nexik commented
musisz zaladowac .env jakos: 

mozna na poziomie systemu operacyjnego np. w linuxie:

```
source .env
```

Tak to sie robi na produkcji w wiekszosci przypadkow. Przy srodowisku developerskiego mozna skorzystac z https://symfony.com/doc/current/components/dotenv.html

2017-12-10 18:54 UTC, Drunken-Dragon commented
Nowy PR https://github.com/Drunken-Dragon/silex-lp/pull/8

W dniu 10 grudnia 2017 19:17 użytkownik Tomasz Ślązok <
notifications@github.com> napisał:

> musisz zaladowac .env jakos:
>
> mozna na poziomie systemu operacyjnego np. w linuxie:
>
> source .env
>
> Tak to sie robi na produkcji w wiekszosci przypadkow. Przy srodowisku
> developerskiego mozna skorzystac z https://symfony.com/doc/
> current/components/dotenv.html
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/Drunken-Dragon/silex-lp/pull/6#issuecomment-350567324>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AWj0bF_ack0xRWC9FrQSgVWJ_29zE2naks5s_CAggaJpZM4Q4xia>
> .
>