Login form
Drunken-Dragon/silex-lp pull request #9
Opened 2017-12-11 14:51 UTC by Drunken-Dragon

Próbuję utworzyć formularz logowania jako odrębną klasę, tak żeby form nie był tworzony w AuthController.

Nie mam żadnego komunikatu błędu, jednak rout /form kieruje mnie na pustą stronę...Co mi umyka?

2017-12-12 17:02 UTC, nexik commented
w  https://github.com/Drunken-Dragon/silex-lp/blob/cc149fb3544af548c26094c0e9cafb22135bb86d/src/routes.php nie ma zdefiniowanego route dla "/form" wiec nie ma sie co odpalic

2017-12-12 17:12 UTC, nexik requested changes

2017-12-12 17:12 UTC, nexik commented on src/Controller/AuthController.php
> +    public function __construct($app, $db, $session, $twig)
brakuje 5 parametru: \Myspace\LoginForm $form

2017-12-12 17:56 UTC, nexik commented
formularz buduje sie w nastepujacy sposob. Do controllera przekazujesz form.factory, a w kontrolerze odpalasz: 

**UWAGA uzylem dwóch spacji zamiast 4 aby zmiescilo sie w komentarzu formatowanie.**
**UWAGA 2: Kod zakłada zaimportowanie komponentu symfony/validator za pomoca composera** 

```php
class LoginController
{
  public function indexAction(Request $request)
  {
     $data = new Form\LoginRequest();
     $form = $this->formFactory->create(Form\LoginType::class, $data);
     $form->handleRequest($request)

     if ($form->isSubmitted() && $form->isValid()) {
       // do some base with $data object
     }
        
     return $this->twig->render('login.html.twig', ['form' => $form->createView()]);
  }
}
```

```php
namespace Form;

class LoginType extends \Symfony\Component\Form\AbstractType
{
  public function buildForm(FormBuilderInterface $builder, array $options): void
  {
    $builder
      ->add('login', TextType::class)
      ->add('password', PasswordType::class)
      ->add('save', SubmitType::class);
  }
}
```

```php
namespace Form;

use Symfony\Component\Validator\Constraints as Assert;

class LoginRequest
{
  /**
   * @Assert\NotBlank()
   * @Assert\Length(min="10", max="100")
   */
  public $login;

  /**
   * @Assert\NotBlank()
   */
  public $password;
}
```

2017-12-13 10:04 UTC, Drunken-Dragon commented
A different method chosen, that branch is to be closed.

2017-12-13 10:04 UTC, closed without merging